# This is an example of a configuration which only holds the configuration data of
# a singular multipart balloon. This is a train balloon that has a head, body, and tail.
train:
  type: multipart # The type of balloon, this must be multipart for multipart balloons
  id: train
  permission: balloon.train
  name: '<white>Train Balloon'
  lore:
    - '&8Bloons Default Balloon'
    - ''
    - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'
  node-count: 5 # The amount of nodes/models in the balloon including the head and tail
  distance-between-nodes: 2.0 # The distance between nodes/models in blocks
  leash-height-from-player: 1.5 # The height of the leash from the zero relative to the balloon
  head-node-offset: 0.0 # The offset of length of head node segments in blocks
  body-node-offset: 0.0 # The offset of length of body node segments in blocks
  tail-node-offset: 0.0 # The offset of length of tail node segments in blocks
  max-joint-angle: 35.0 # The max angle in degrees of freedom for each joint between nodes
  y-axis-interpolation: 0.2 # The amount of interpolation between nodes on the Y axis (must be between 0.0 and 1.0)
  turning-spline-interpolation: 0.5 # The amount of interpolation for the spline when turning
  passive-sine-wave-speed: 0.05 # The speed of the passive sine wave
  passive-sine-wave-amplitude: 0.5 # The amplitude of the passive sine wave
  passive-nose-sine-wave-amplitude: 0.5 # The amplitude of the passive sine wave for the nose
  head: # Head must be supplied for a balloon of this kind
    material: LEATHER_HORSE_ARMOR # The material of the head
    color: '#FF0000' # The color of the head item, this is optional
    custom-model-data: 10280 # The custom model data of the head, this is not required but is recommended for use of models
  body: # Body must be supplied for a balloon of this kind
    material: LEATHER_HORSE_ARMOR # The material of the body
    color: '#ffffff' # The color of the body, this is optional
    custom-model-data: 10281 # The custom model data of the body, this is not required but is recommended for use of models
  tail: # Tail must be supplied for a balloon of this kind
    material: LEATHER_HORSE_ARMOR # The material of the tail
    color: '#ffffff' # The color of the tail, this is optional
    custom-model-data: 10282 # The custom model data of the tail, this is not required but is recommended for use of models