# --------------------------------------------------#
#
# Bloons 2.2.3
# Made by Jeqo
#
# Wiki:        https://jeqo.net/wiki
# Discord:     https://jeqo.net/discord
#
# Default Assets Made by TwistedDreams
# Get custom balloons and more for your server:
# https://mcmodels.net/vendors/pixelsonpoint/
#
# --------------------------------------------------#
#                     SETTINGS                      #
# --------------------------------------------------#
#
# Send a message to operators when they join if there is a Bloons update.
check-for-updates: true
# The language file to load. This will be used for all messages in the plugin.
language: en_US
# Do you want to close the menu when a player equips a balloon?
close-on-equip: true
# Do you want to close the menu when a player unequips a balloon?
close-on-unequip: true
# Do you want to hide balloons that the player does not have permission for?
hide-balloons-without-permission: true
# Title for the balloons menu.
menu-title: "&f"
# Amount of slots per page. Valid values: 27, 36, 45, and 54. 9 of these slots will be used for the menu buttons.
menu-size: 54
# Amount of slots from the top that you want the balloons to appear in. Valid values: 9, 18, 27, 36, and 45.
# This has the be at least 9 less than the menu-size!
balloon-slots: 45
# Notice: Keep buttons in the last row of your entire menu to avoid any bugs!
buttons:
  previous-page:
    material: FLINT
    custom-model-data: "previous_page"
    name: '&7← ᴘʀᴇᴠɪᴏᴜs ᴘᴀɢᴇ'
    slots:
      - 48
  unequip:
    material: FLINT
    custom-model-data: "unequip"
    name: '&7ᴜɴᴇǫᴜɪᴘ ʙᴀʟʟᴏᴏɴ'
    slots:
      - 49
  next-page:
    material: FLINT
    custom-model-data: "next_page"
    name: '&7ɴᴇxᴛ ᴘᴀɢᴇ →'
    slots:
      - 50