# --------------------------------------------------#
#
# Bloons 1.0.3-BETA
# Made by Jeqo
#
# Wiki:     https://jeqo.net/wiki/bloons
# Discord:     https://jeqo.net/discord
#
# Default Assets Made by TwistedDreams
# Get custom balloons and more for your server:
# https://mcmodels.net/vendors/pixelsonpoint/
#
# --------------------------------------------------#
#                     SETTINGS                      #
# --------------------------------------------------#
#
# Do you want to close the menu when a player equips a balloon?
close-on-equip: true
# Do you want to close the menu when a player unequips a balloon?
close-on-unequip: true
# Do you want to hide balloons that the player does not have permission for?
hide-balloons-without-permission: true
# Title for the balloons menu.
menu-title: "&f"
# Amount of slots per page. Valid values: 27, 36, 45, and 54. 9 of these slots will be used for the menu buttons.
menu-size: 54
# Amount of slots from the top that you want the balloons to appear in. Valid values: 9, 18, 27, 36, and 45.
balloon-slots: 45
#
# Notice: Keep buttons in the last row of your entire menu to avoid any bugs!
buttons:
  previous-page:
    material: FLINT
    custom-model-data: 2
    name: '&7← ᴘʀᴇᴠɪᴏᴜs ᴘᴀɢᴇ'
    slots:
      - 48
  unequip:
    material: FLINT
    custom-model-data: 3
    name: '&7ᴜɴᴇǫᴜɪᴘ ʙᴀʟʟᴏᴏɴ'
    slots:
      - 49
  next-page:
    material: FLINT
    custom-model-data: 4
    name: '&7ɴᴇxᴛ ᴘᴀɢᴇ →'
    slots:
      - 50
#
# --------------------------------------------------#
#                     MESSAGES                      #
# --------------------------------------------------#
#
messages:
  prefix: '#ff00cc[#e70cd3B#ce18dbl#b624e2o#9e31e9o#863df0n#6d49f8s#5555ff] &r'
  no-permission: '#fc1c1cAccess denied.'
  player-not-found: '#fc1c1cPlayer not found.'
  config-reloaded: '&aConfig reloaded!'
  # Balloon related messages.
  equipped: '%s &aequipped!'
  unequipped: '&aYour balloon has been stored safely.'
  balloon-not-found: '#fc1c1cBalloon not found.'
  not-equipped: '#fc1c1cYou do not currently have a balloon equipped.'
#
# --------------------------------------------------#
#                     BALLOONS                      #
# --------------------------------------------------#
#
# Balloons can be dyed by adding a color option with a hex value and setting the material to any leather item.
# Valid leather items: LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_HORSE_ARMOR
balloons:
  blue:
    id: blue
    permission: balloon.blue
    material: FLINT
    custom-model-data: 5
    name: '&bBlue &fBalloon'
    lore:
      - '&8Bloons Default Balloon'
      - ''
      - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'
  green:
    id: green
    permission: balloon.green
    material: FLINT
    custom-model-data: 6
    name: '&aGreen &fBalloon'
    lore:
      - '&8Bloons Default Balloon'
      - ''
      - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'
  pink:
    id: pink
    permission: balloon.pink
    material: FLINT
    custom-model-data: 7
    name: '&dPink &fBalloon'
    lore:
      - '&8Bloons Default Balloon'
      - ''
      - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'
  yellow:
    id: yellow
    permission: balloon.yellow
    material: FLINT
    custom-model-data: 8
    name: '&eYellow &fBalloon'
    lore:
      - '&8Bloons Default Balloon'
      - ''
      - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'
  dyeable_example:
    id: dyeable_example
    permission: balloon.dyeable
    material: LEATHER_HORSE_ARMOR
    color: '#ffffff'
    custom-model-data: 1
    name: '#ffffffDyeable Balloon'
    lore:
      - '&8Bloons Example Balloon'
      - ''
      - '&eᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ'