# --------------------------------------------------#
#
# Bloons 2.0.0
# Made by Jeqo
#
# Wiki:     https://jeqo.net/wiki/bloons
# Discord:     https://jeqo.net/discord
#
# Default Assets Made by TwistedDreams
# Get custom balloons and more for your server:
# https://mcmodels.net/vendors/pixelsonpoint/
#
# --------------------------------------------------#
#                     SETTINGS                      #
# --------------------------------------------------#
#
# Send a message to operators when they join if there is a Bloons update.
check-for-updates: true
# Do you want to close the menu when a player equips a balloon?
close-on-equip: true
# Do you want to close the menu when a player unequips a balloon?
close-on-unequip: true
# Do you want to hide balloons that the player does not have permission for?
hide-balloons-without-permission: true
# Title for the balloons menu.
menu-title: "<white>"
# Amount of slots per page. Valid values: 27, 36, 45, and 54. 9 of these slots will be used for the menu buttons.
menu-size: 54
# Amount of slots from the top that you want the balloons to appear in. Valid values: 9, 18, 27, 36, and 45.
# This has the be at least 9 less than the menu-size!
balloon-slots: 45
# Notice: Keep buttons in the last row of your entire menu to avoid any bugs!
buttons:
  previous-page:
    material: FLINT
    custom-model-data: 2
    name: '<gray>← ᴘʀᴇᴠɪᴏᴜs ᴘᴀɢᴇ'
    slots:
      - 48
  unequip:
    material: FLINT
    custom-model-data: 3
    name: '<gray>ᴜɴᴇǫᴜɪᴘ ʙᴀʟʟᴏᴏɴ'
    slots:
      - 49
  next-page:
    material: FLINT
    custom-model-data: 4
    name: '<gray>ɴᴇxᴛ ᴘᴀɢᴇ →'
    slots:
      - 50
#
# --------------------------------------------------#
#                     MESSAGES                      #
# --------------------------------------------------#
#
messages:
  prefix: '<gradient:#ff00cc:#5555ff>[Bloons]</gradient> <white>'
  no-permission: '<#fc1c1c>Access denied.'
  player-not-found: '<#fc1c1c>Player not found.'
  config-reloaded: '<green>Config reloaded.'
  # Balloon related messages.
  equipped: '%s <green>equipped!'
  unequipped: '<green>Your balloon has been stored safely.'
  balloon-not-found: '<#fc1c1c>Balloon not found.'
  not-equipped: '<#fc1c1c>You do not currently have a balloon equipped.'