# --------------------------------------------------#
#
# Bloons 1.0.0-BETA
# Made by Jeqo and TwistedDreams
#
# Wiki:     https://jeqo.net/wiki/bloons
# Discord:     https://jeqo.net/bloonsdiscord
#
# --------------------------------------------------#
#                     BALLOONS                      #
# --------------------------------------------------#
#
balloons:
  blue:
    material: FLINT
    custom-model-data: 1
    permission: balloon.blue
  green:
    material: FLINT
    custom-model-data: 2
    permission: balloon.green
  yellow:
    material: FLINT
    custom-model-data: 3
    permission: balloon.yellow
  pink:
    material: FLINT
    custom-model-data: 4
    permission: balloon.pink
#
# --------------------------------------------------#
#                     MESSAGES                      #
# --------------------------------------------------#
#
messages:
  prefix: '#ff00cc[#e207c5B#c50fbdl#a816b6o#8a1dafo#6d24a8n#502ca0s#333399] &r'
  no-permission: '#ee0000You do not have permission to use this balloon.'
  player-not-found: '#ee0000Player not found.'
  usage: '&7Usage: /balloon [equip/unequip] <balloon>'
  config-reloaded: '&aConfig reloaded!'
  # Balloon related messages.
  equipped: '&a%s balloon equipped!'
  unequipped: '#ee0000Your balloon has been stored safely.'
  balloon-not-found: '#ee0000Balloon not found.'
  not-equipped: '#ee0000You do not currently have a balloon equipped.'