name: Publish Package to GitHub Packages

# Triggered on pushes to main
on:
  push:
    branches: [ "main" ]

# Jobs are only triggered when the commit message starts with 'feat'
jobs:
  # Publishes the package to GitHub Packages
  publish:
    name: Publish Package
    if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
    runs-on: ubuntu-latest
    environment: jdk21-publishing
    permissions:
      contents: read
      packages: write

    # This job publishes the package to GitHub Packages via mvn deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}